# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  nugetApiKey: 'oy2ffxowd5sfnarduoyqvp6sm7xmqqnermdt6cek2m2uve'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration)'
- script: dotnet test Test.Ssin.Belgium/Test.Ssin.Belgium.csproj
  displayName: 'Run UTs'
- script: dotnet nuget push -s https://www.nuget.org -k $(nugetApiKey) --skip-duplicate Ssin.Belgium/bin/Release/*.nupkg
  displayName: 'Push nuget to nuget.org'
  
